# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-TrayIcon
version:      0.06
version_from: TrayIcon.pm
installdirs:  site
requires:
    Gtk2:                          0.96

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
